### ISSUE TITLE
DeviceView.js is missing

### ISSUE THREAD

**Issue by shahzadns** [FamousArchives/generator-famous#34]
Hi, i can not require the "./DeviceView" 
//var DeviceView    = require('./DeviceView');

it throws an error 404 not found.
Uncaught Error: Script error for: DeviceView
http://requirejs.org/docs/errors.html#scripterror

**Comment by amirmata** [comment]
Did anyone manage to get the DeviceView.js
I am trying to follow the OBJLoader tutorial and it looks like I can't go any further without it!

**Comment by MylesBorins** [comment]
this repo is deprecated.

the generator was created for the old version of famous. please follow the
instructions in the tutorial and clone the appropriate repo associated with
the lesson.
