### ISSUE TITLE
Feature: Support for Unit/Integration Testing

### ISSUE THREAD

**Issue by KraigWalker** [FamousArchives/generator-famous#36]
Testing is important. Like... Wearing a seatbelt or something.

Other projects like phonegap don't just scaffold a basic project to start with, but they also include a test.js file and bundle in the required modules/runners.

It'd be really great if generator-famous could do that as well, to ensure devs old and new can build on a concrete foundation.

**Comment by MylesBorins** [comment]
@KraigWalker would you be willing to close this?
